version: '3'

services:
  actix-web-demo:
    build:
      dockerfile: Dockerfile
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
