version: '3'

services:
  actix-web-demo:
    build: .
    ports:
      - 0.0.0.0:8080:8080
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  jaeger:
    image: jaegertracing/all-in-one:1.37
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
