version: '3'

services:
  actix-web-demo:
    build: .
    ports:
      - 0.0.0.0:8080:8080
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
